# Replace these values with the output of the setup.ps1 script

@advanceWorkflowUrl=https://prod-20.uksouth.logic.azure.com:443/workflows/16cd5ad5c77e4970b69c228e24a5c3f7/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=KzNGVm-NaMjC2wZ8T0lmwHyT3AQz9yeedZVbJJLZYG8
# Call the Advance Workflow with an unknown id to start the state machine

POST {{advanceWorkflowUrl}}
Content-Type: application/json

{
    "itemId" : "42"
}

###

# Call the Advance Workflow endpoint a couple of times to move through the 2 states and then have the base complete

###

POST {{advanceWorkflowUrl}}
Content-Type: application/json

{
    "itemId" : "42",
    "assignedTo" : "matt",
    "newState": "STAGE2"
}

###

POST {{advanceWorkflowUrl}}
Content-Type: application/json

{
    "itemId" : "42",
    "assignedTo" : "matt",
    "newState": "DONE"
}




