# Replace these values with the output of the setup.ps1 script

@advanceWorkflowUrl=https://prod-26.uksouth.logic.azure.com:443/workflows/3d1e85c667ac47dabf94ed96500a143d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=WPWkdwvp2OmMngLCwQRpLB_kNiwBfDUT3FkckqVd0wE
# Call the Advance Workflow with an unknown id to start the state machine

POST {{advanceWorkflowUrl}}
Content-Type: application/json

{
    "itemId" : "42"
}

###

# Call the Advance Workflow endpoint a couple of times to move through the 2 states and then have the base complete

###

POST {{advanceWorkflowUrl}}
Content-Type: application/json

{
    "itemId" : "42",
    "assignedTo" : "matt",
    "newState": "STAGE2"
}

###

POST {{advanceWorkflowUrl}}
Content-Type: application/json

{
    "itemId" : "42",
    "assignedTo" : "matt",
    "newState": "DONE"
}




